bicycle/bicycle/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static

from bicycle import settings

# настройки для отображения в админке вместо слов "Администрирование" и др.
admin.site.site_header = 'ГлаВВелосипеД'
admin.site.index_title = 'Вы - прекрасный администратор'

urlpatterns = [
    # расширяем и изменяем работу встроенного приложения django.contrib.auth,
    # если какой-то URL не обнаружится в приложении users — Django пойдёт
    # искать его в django.contrib.auth - этот путь идет ниже, через один.
    path('auth/', include('users.urls', namespace='users')),
    # подключаем 'auth' чтобы дать пользователям доступ к страницам приложения
    # вместо префикса auth/ можно установить любой другой, но хорошим тоном
    # будет установить префикс, который совпадает с именем приложения,
    # обрабатывающего URL
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('bikes.urls', namespace='bikes')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('captcha/', include('captcha.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# переопределяем страницы ошибок, вместо стандартных делаем свои - красивые!
handler404 = "bikes.views.page_not_found" # noqa
handler500 = "bikes.views.server_error"   # noqa

bicycle/bikes/urls.py
from django.urls import path

from bikes import views

app_name = 'bikes'

urlpatterns = [
    path('', views.index, name='index'),
    path('filter/', views.filter, name='filter'),
    path('about/', views.about, name='about'),
    path('happy_bonus_bike/', views.bonus_bike, name='bonus_bike'),
    path('brand/<slug:brand_slug>/', views.brand_group, name='brand_group'),
    path('veloformat/<format>/', views.veloformat, name='format'),
    path('brand/<slug:brand_slug>/<slug:model_slug>/',
         views.model_detail, name='model_detail'),
    path('for/<sex_age>/', views.sex_age_group, name='sex_age_group'),
    path('price/<price>/', views.price_group, name='price_group'),
]

bicycle/feedback/urls.py
from django.urls import path

from feedback import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback_posts, name='feedback_posts'),
    path('create/', views.create, name='create'),
]

bicycle/users/urls.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    # смена пароля
    path('password_change/', PasswordChangeView.as_view(
         template_name='users/password_change_form.html'),
         name='password_change'),
    # смена пароля прошла успешно
    path('password_change/done/', PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),
    # сброс пароля
    path('password_reset/', PasswordResetView.as_view(
         template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    # уведомление об отправке ссылки для восстановления пароля на почту
    path('password_reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'),
         name='reset_done'),
    # подтверждение сброса пароля
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'),
         name='reset_confirm'),
    # уведомление, что пароль изменен
    path('reset/done/', PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'),
         name='reset_complete'),
]

bicycle/templates/includes/carousel.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box}
body {font-family: Verdana, sans-serif; margin:0}
.mySlides {display: none}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1536px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 18px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
  top: 30%;

}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
</style>
</head>
<body>

<div class="slideshow-container">

<div class="mySlides fade">
  <a href="{% url 'bikes:bonus_bike' %}">
  <div class="numbertext">1 / 4</div>
  <img style="width:100%" src="{% static "img/site/1.jpg"%}">
  <div class="text" style="text-shadow: 1px 1px 2px black;">Счастливый час!<br>Каждый час - новый велосипед со скидкой!</div>
  </a>
</div>

<div class="mySlides fade">
  <a href="{% url 'bikes:bonus_bike' %}">
  <div class="numbertext">2 / 4</div>
  <img style="width:100%" src="{% static "img/site/2.jpg"%}">
  <div class="text" style="text-shadow: 1px 1px 2px black;">Скидка выбирается случайным образом <br>в диапазоне от 10% до 50%</div>
</div>

<div class="mySlides fade">
  <a href="{% url 'bikes:bonus_bike' %}">
  <div class="numbertext">3 / 4</div>
  <img style="width:100%" src="{% static "img/site/3.jpg"%}">
  {% for i in choose_happy_bike %}
  <div class="text" style="text-shadow: 1px 1px 2px black;">На данный момент велосипед: {{ i.brand }}-{{ i.model }} <br> со скидкой {{ discount }}% и ценой: <s>{{ i.price }}</s> {{new_price}} </div>
  {% endfor %}
</div>

<div class="mySlides fade">
  <a href="{% url 'bikes:bonus_bike' %}">
  <div class="numbertext">4 / 4</div>
  <img style="width:100%" src="{% static "img/site/2.jpg"%}">
  <div class="text" style="text-shadow: 1px 1px 2px black;"> Данный сайт - учебный проект для портфолио.<br>Вопросы, пожелания и предложения можно отправить на pvnick@yandex.ru<br>Или оставить прямо на сайте</div>
</div>

<a class="prev" onclick="plusSlides(-1)">❮</a>
<a class="next" onclick="plusSlides(1)">❯</a>

</div>
<br>

{% comment %} <div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div> {% endcomment %}

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>

</body>
</html> 

bicycle/templates/includes/filter_bar.html
<form action="{% url 'bikes:filter' %}" method="GET">
    <div style="border: black solid 1px; padding: 3px; font-size: 14px">
      <div>
        
        <select name="brand" style="color: gray; width: 150px">
          <option disabled selected>Выбрать брэнд</option>
          {% for i in distinct_brand %}
          <option value="{{ i.brand }}">{{ i.brand }}</option>
          {% endfor %}
        </select>
  
        <select name="veloformat" style="color: gray; width: 120px;">
          <option disabled selected>Формат</option>
          {% for i in distinct_veloformat %}
          <option value="{{ i.veloformat }}">{{ i.veloformat }}</option>
          {% endfor %}
        </select>
  
        <select name="sex_age" style="color: gray; width: 120px">
          <option disabled selected>Пол/Возраст</option>
          {% for i in distinct_sex_age %}
          <option value="{{ i.sex_age }}">{{ i.sex_age }}</option>
          {% endfor %}
        </select>

        <input type="number" style="width: 120px" step='100' placeholder=' Цена от' name='price__gt'>
        <input type="number" style="width: 120px" step='100' placeholder=' Цена до' name='price__lt'>
  
        <button type="submit">Поехали</button>
        <button type="reset">Сбросить</button>

      </div>
    </div>
  </form>

bicycle/templates/includes/footer.html
{% load static %}

<footer class="footer">
    <p>©ГлаВВелосипеД {{ year }}</p>
</footer>

bicycle/templates/includes/header.html
<style>
  .container-for-header {
    display: flex;
    justify-content:space-around;
  }

  .box-2 {
    margin:5px;
  }

  .box-3 ul li, .box-1 ul li {
    display: inline;
    font-size: 1.4vw;
  }

  .box-1, .box-3 {
    padding-top: 2vw;
  }
</style>

<header class="container-for-header">
  <div class="box-1">
    <ul>
      <li><a href="{% url 'bikes:about' %}">О сайте! </a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'feedback:feedback_posts' %}">  Отзывы/</a><a href="{% url 'feedback:create' %}"style="color: red;">Написать</a></li>
      {% else %}
      <li><a href="{% url 'feedback:feedback_posts' %}">  Отзывы </a></li>
      {% endif %}
    </ul>
  </div>
  <div class="box-2">
      <div class="header">
        <a href="{% url 'bikes:index' %}">ГлаВВелосипеД</a>
      </div>
  </div>
  <div class="box-3">
    {% if user.is_authenticated %}
    <ul>
      <li><a style="color: red;" href="{% url 'users:logout' %}">{{ user.username|truncatechars:6 }}  </a></li>
      <li><a href="{% url 'users:password_reset_form' %}"> Изменить пароль</a></li>
    </ul>
    {% else %}
      <ul>
        <li><a href="{% url 'users:login' %}">Войти </a></li>
        <li><a href="{% url 'users:signup' %}"> Регистрация</a></li>
      </ul>
    {% endif %}
  </div>
</header>

bicycle/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" >
    <ul class="paginate-container">
      {% if page_obj.has_previous %}
        <li><a href="?page=1" style="text-decoration: none !important;">Первая</a></li>
        <li>
          <a href="?page={{ page_obj.previous_page_number }}" style="text-decoration: none !important;">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li >
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li>
            <a href="?page={{ i }}" style="text-decoration: none !important;">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li >
          <a href="?page={{ page_obj.next_page_number }}" style="text-decoration: none !important;">
            Следующая
          </a>
        </li>
        <li>
          <a href="?page={{ page_obj.paginator.num_pages }}" style="text-decoration: none !important;">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

bicycle/templates/includes/specifications.html
<ul>
  <li><a href="{% url 'bikes:brand_group' i.brand_slug %}">Брэнд: {{ i.brand }}</a></li>
  <li>
  {% comment %} В url ставим в ковычках ссылку адреса назначения, т.е. по этой ссылке будет отрабатывать адрес из url
  далее передаем аттрибуты для слагов {% endcomment %}
  <a href="{% url 'bikes:model_detail' i.brand_slug i.model_slug %}">Модель: {{i.model}}</a></li>
  <li><a href="{% url 'bikes:format' i.veloformat %}">Формат: {{ i.veloformat }}</a></li>
  <li><a href="{% url 'bikes:sex_age_group' i.sex_age %}">Пол & Возраст: {{ i.sex_age }}</a></li>
  <li><a href="{% url 'bikes:price_group' i.price %}"> Цена: {{ i.price }}</a></li>
</ul>